//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        public System.Guid Id { get; set; }
        public int Version { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
        public bool IsDeleted { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte[] FiscalYearEnd { get; set; }
        public bool IsLocked { get; set; }
        public int WorkflowStatus { get; set; }
        public bool IsOffline { get; set; }
    }
}
